---
- name: Check if MongoDB is installed
  win_service:
    name: MongoDB
  register: mongodb_service
  ignore_errors: true

 #path: 'https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-6.0.6-signed.msi'

- name: Install MongoDB
  win_package:
    path: '{{ mongodb_package_url }}'
    state: present
    arguments: /l*v mdbinstall.log /qb ADDLOCAL="ServerService"
  become: true
  become_method: runas
  become_user: SYSTEM
  when: mongodb_service.exists == false

- name: Check if mongosh is installed
  win_command: mongosh --version
  register: mongosh_installed
  ignore_errors: yes

- name: Download mongosh installer
  win_get_url:
    url: "{{ mongosh_package_url }}"
    dest: "C:\\temp\\mongosh.msi"
  when: mongosh_installed.failed

- name: Install mongosh
  win_package:
    path: "C:\\temp\\mongosh.msi"
    state: present
  when: mongosh_installed.failed

- name: Check if MongoDB Compass is installed
  win_command: |
    if (Get-Command "C:\\Program Files\\MongoDB Compass\\MongoDBCompass.exe" -ErrorAction SilentlyContinue) {
      Write-Output "MongoDB Compass is installed"
    } else {
      Write-Error "MongoDB Compass is not installed"
    }
  register: compass_installed
  ignore_errors: yes

- name: Download MongoDB Compass installer
  win_get_url:
    url: "https://downloads.mongodb.com/compass/mongodb-compass-1.31.2-win32-x64.msi"
    dest: "C:\\temp\\mongodb-compass.msi"
  when: compass_installed.failed

- name: Install MongoDB Compass
  win_package:
    path: "C:\\temp\\mongodb-compass.msi"
    state: present
  when: compass_installed.failed

- name: Ensure MongoDB service is runnings
  win_service:
    name: MongoDB
    state: started
    start_mode: auto

- name: Create MongoDB script files for each database
  win_copy:
    content: |
      db = connect('mongodb://localhost:27017/admin');
      db = db.getSiblingDB('admin');

      // Drop the user if it exists
      if (!db.getUser('{{ db_user }}')) {
        // Create the user under admin db
        db.createUser({
          user: "{{ db_user }}",
          pwd: "{{ db_password }}",
          roles: [{ role: "readWrite", db: "{{ item }}" }]
        });

        // Retrieve the user
        db.getUser("{{ db_user }}");
      }

      db = db.getSiblingDB('{{ item }}');

      // Drop the user if it exists
      if (db.getUser('{{ db_user }}')) {
        db.dropUser('{{ db_user }}');
      }

      // Drop the database if it exists
      db.dropDatabase();

      // Re-create the database by inserting a document
      if('{{ item }}' == 'AlchemyIntegrationService'){
        db.BicDirectory.insertOne({ created: true }); // This creates the database if it doesn't exist
      }else{
        db.test.insertOne({ created: true }); // This creates the database if it doesn't exist
      }
    dest: 'C:\temp\mongo_script_{{ item }}.js'
  with_items: "{{ db_names }}"

- name: Create PowerShell script files to run MongoDB scripts for each database
  win_copy:
    content: |
      Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      $mongoshExe = "{{ mongosh_path }}"
      $scriptPath = "C:\\temp\\mongo_script_{{ item }}.js"
      Write-Output "Starting MongoDB script execution for {{ item }}"
      & $mongoshExe $scriptPath
      Write-Output "Completed MongoDB script execution for {{ item }}"
    dest: 'C:\temp\run_mongo_psw_script_{{ item }}.ps1'
  with_items: "{{ db_names }}"

- name: Run PowerShell scripts with mongosh for each database
  win_shell: |
    powershell.exe -File C:\temp\run_mongo_psw_script_{{ item }}.ps1
  register: mongo_script_output
  with_items: "{{ db_names }}"
  loop_control:
    loop_var: item
  timeout: 600

- name: Display MongoDB script output
  debug:
    msg: "{{ item }} output: {{ item_output.stdout }}"
  with_items: "{{ mongo_script_outputs.results }}"
  loop_control:
    loop_var: item_output

- name: Display MongoDB script errors
  debug:
    msg: "{{ item }} errors: {{ item_output.stderr }}"
  with_items: "{{ mongo_script_outputs.results }}"
  loop_control:
    loop_var: item_output

# - name: Run MongoDB script file
#   win_shell: |
#     $mongoshExe = "{{ mongosh_exe }}"
#     $scriptPath = "C:\temp\mongo_script.js"
#     & $mongoshExe  "$scriptPath"
#   register: db_output

# - name: Remove MongoDB script file
#   win_file:
#     path: 'C:\temp\mongo_script.js'
#     state: absent

# - name: Print output
#   debug:
#     var: db_output
