---
- name: Check if MongoDB is installed
  win_service:
    name: MongoDB
  register: mongodb_service
  ignore_errors: true

 #path: 'https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-6.0.6-signed.msi'

- name: Install MongoDB
  win_package:
    path: '{{ mongodb_package_url }}'
    state: present
    arguments: /l*v mdbinstall.log /qb ADDLOCAL="ServerService"
  become: true
  become_method: runas
  become_user: SYSTEM
  when: mongodb_service.exists == false

- name: Check if mongosh is installed
  win_command: mongosh --version
  register: mongosh_installed
  ignore_errors: yes

- name: Download mongosh installer
  win_get_url:
    url: "{{ mongosh_package_url }}"
    dest: "C:\\temp\\mongosh.msi"
  when: mongosh_installed.failed

- name: Install mongosh
  win_package:
    path: "C:\\temp\\mongosh.msi"
    state: present
  when: mongosh_installed.failed

- name: Check if MongoDB Compass is installed
  win_command: |
    if (Get-Command "C:\\Program Files\\MongoDB Compass\\MongoDBCompass.exe" -ErrorAction SilentlyContinue) {
      Write-Output "MongoDB Compass is installed"
    } else {
      Write-Error "MongoDB Compass is not installed"
    }
  register: compass_installed
  ignore_errors: yes

- name: Download MongoDB Compass installer
  win_get_url:
    url: "https://downloads.mongodb.com/compass/mongodb-compass-1.31.2-win32-x64.msi"
    dest: "C:\\temp\\mongodb-compass.msi"
  when: compass_installed.failed

- name: Install MongoDB Compass
  win_package:
    path: "C:\\temp\\mongodb-compass.msi"
    state: present
  when: compass_installed.failed

- name: Ensure MongoDB service is runnings
  win_service:
    name: MongoDB
    state: started
    start_mode: auto

- name: Create MongoDB script file
  win_copy:
    content: |
      db = connect( 'mongodb://localhost:27017/testdb' );
      use {{ db_name }};
      db.createUser({
        user: "{{ db_user }}",
        pwd: "{{ db_password }}",
        roles: [{ role: "readWrite", db: "{{ db_name }}" }]
      });
      db.getUser("{{ db_user }}");
    dest: 'C:\temp\mongo_script.js'

- name: Run MongoDB script with mongosh
  win_shell: |
    $mongoshExe = (Get-Command mongosh).Source
    $connectionString = "mongodb://localhost:27017/testdb"
    $scriptPath = "C:\\temp\\mongo_script.js"
    & $mongoshExe $connectionString $scriptPath
  args:
    executable: powershell.exe
  register: mongo_script_output

- name: Display MongoDB script output
  debug:
    msg: "{{ mongo_script_output.stdout }}"

# - name: Run MongoDB script file
#   win_shell: |
#     $mongoshExe = "{{ mongosh_exe }}"
#     $scriptPath = "C:\temp\mongo_script.js"
#     & $mongoshExe  "$scriptPath"
#   register: db_output

# - name: Remove MongoDB script file
#   win_file:
#     path: 'C:\temp\mongo_script.js'
#     state: absent

# - name: Print output
#   debug:
#     var: db_output
